### ISSUE TITLE
Feature Request - Add segments to existing line / shape segments

### ISSUE THREAD

**Issue by louiesolomon** [design4use/gb-sketch-segmentcircle#1]
Really great plugin. Thanks for sharing!

It would be useful to be able to add a specific amount of evenly spaced segments between existing segments on a line or shape.

For example, select two segments of a shape, run plugin, and choose how many segments to add between the selected segments.

Alternatively, select an entire shape, and have chosen amount of segments appear between every segment of the shape.

**Comment by design4use** [comment]
Great idea, let me think about that. Agree that'd be great to have :)

**Comment by design4use** [comment]
Variable value segments let you now achieve that in the just released version 2.0. Closing.
