### ISSUE TITLE
Empty folders in Sketch Version 41 (35326)

### ISSUE THREAD

**Issue by stuartwalker559** [design4use/gb-sketch-segmentcircle#12]
Like the title says, when creating any kind of circle it creates an empty folder outside of any artboard. Please fix as your plugin was super useful!

**Comment by mcarlile** [comment]
I'm also experiencing this issue after upgrading to Sketch 41. This plugin has saved me so much time and I use it every day. I'm excited to see a resolution as well!

**Comment by fraspas** [comment]
The plug-in is not working with the latest version of Sketch (ver 41).  It only creates an empty folder, please fix!  This tool is a time saver!

**Comment by LindaGuer** [comment]
Please fix this bug in sketch 41 T___T

**Comment by lukasoppermann** [comment]
Same issue.

**Comment by abearknowshow** [comment]
I'm having the same issue: Sketch Version 41 (35326)

I love your plugin, thank you so much for sharing your genius with us :)

**Comment by mattatgit** [comment]
Yeah i'd love to have an update for Sketch 41. Maybe make it a donationware project ? I'd happily kick in a few dollars to keep this working in future Sketch versions.

**Comment by c01gat3** [comment]
same as others - empty folder in sketch 41

**Comment by mieras** [comment]
You can download and use an older version of Sketch (or make a copy of Sketch before you update)

**Comment by lukasoppermann** [comment]
Why would I want to download the old version? The new one has awesome features like replaceable symbols in symbols.

**Comment by mieras** [comment]
_Why would you want to download the old version?_ To make the segmented circle plugin to work.. It's a work around. I always make a copy / backup of the previous Sketch (application) for this kind of situations. So I create a segmented circle in the old Sketch and copy it to the new one.

**Comment by stuartwalker559** [comment]
I reverted back to previous version of sketch as there are currently too many bugs. You can do this easily by going here - https://www.sketchapp.com/updates/

**Comment by design4use** [comment]
Issue is now solved. The Segmented Circles plugin has just been updated to work with the new Sketch v41.2 and earlier. 
Get it at https://github.com/design4use/gb-sketch-segmentcircle

**Comment by stuartwalker559** [comment]
@design4use Appreciate the update!
