### ISSUE TITLE
Empty folders gets created outside the artboard with mac os sierra version (10.12) and sketch version 40.3

### ISSUE THREAD

**Issue by Pavithra-olety** [design4use/gb-sketch-segmentcircle#16]
Hi,

The plugin creates empty folders gets created outside the artboard with mac os sierra version (10.12) and sketch version 40.3. Any help?

Thanks,
Pavithra

**Comment by windhorseguide** [comment]
I'm having the same problem. Another issue is: I used the plugin for variable segmented circle, but now I can't get the dialog box to show for that option. Thanks for addressing :)

**Comment by codesweeper** [comment]
same here:
mac os sierra version (10.12)
sketch version 40.1
