### ISSUE TITLE
Sketch 44: Create variable segments circle stopped working

### ISSUE THREAD

**Issue by JetPack33** [design4use/gb-sketch-segmentcircle#19]
Worked fine for a few instances then stopped working all together. Pop-up does not show up. All other options work just fine.

**Comment by pawelkontek** [comment]
I am having the same issue. For me the problem occurs only with "Create Variable Segmented Circle".

**Comment by ryoungblood** [comment]
+1. Have tried un/reinstalling plugin, restarting laptop, clearing cache. No dice so far.

**Comment by ryoungblood** [comment]
+1. Have tried un/reinstalling plugin, restarting laptop, clearing cache. No dice so far.

**Comment by ryoungblood** [comment]
...however, "Reset to Defaults" in the plugin's menu did work.

**Comment by username1290** [comment]
For me it's working, you can download an old version of Sketch and rename it. I.e. [download Sketch 40 or any version](https://www.sketchapp.com/updates/), rename it to sketch.40.app, open the old version, run the plugin. 
You can run the old Sketch.40.app along with the current Sketch.
