### ISSUE TITLE
Not working in Sketch 50

### ISSUE THREAD

**Issue by songcarver** [design4use/gb-sketch-segmentcircle#24]
Not working in Sketch 50. Perhaps some earlier. It produces layer groups, but they are empty.

🙏 Please fix!

**Comment by design4use** [comment]
This was introduced with an Sketch API change in 50. Will have added the fix in a couple of days...

**Comment by marcushasfun** [comment]
Any news?

**Comment by design4use** [comment]
v2.04 solves the issue and now works with the updated Sketch 50 API

**Comment by songcarver** [comment]
@design4use 🙏 Thank you, this is very appreciated!
