### ISSUE TITLE
No layers produced in Sketch 52

### ISSUE THREAD

**Issue by chuckflores** [design4use/gb-sketch-segmentcircle#28]
This is an issue since the Sketch 52 update. It includes 52.1. Tested on 2 separate machines.

Running any of the circle options via the plug in creates a folder of the selected circle however no layers are created inside the generated circle folders.

<img width="2022" alt="screen shot 2018-10-04 at 2 06 40 pm" src="https://user-images.githubusercontent.com/8375840/46493736-1f34f980-c7df-11e8-9093-1d3f5681010a.png">

**Comment by TVL-2K** [comment]
Same

**Comment by seanrmsy** [comment]
Same.

**Comment by jjato** [comment]
Same here

**Comment by lucasstinis** [comment]
Same... :(

**Comment by damog** [comment]
Same :(

**Comment by RobertoMSousa** [comment]
👍

**Comment by mcvova** [comment]
Check solution in last pull request

**Comment by mcvova** [comment]
Check solution in last pull request

**Comment by Royalbeck** [comment]
@mcvova I can't get to it (something about permission)
sketch 52.2 won't work

**Comment by jangtrinh** [comment]
The author didn't merge the fix commit to his source though. Gotta wait :(

**Comment by mcvova** [comment]
> The author didn't merge the fix commit to his source though. Gotta wait :(

or you can make this changes manually in your PC

**Comment by surfnostalgia** [comment]
I just updated my Sketch. No!!!! This was the best plug-in. Now its a dud!

**Comment by kashifkiduniya** [comment]
same!

**Comment by hyeashish** [comment]
It's not working! Any update on the fix? I am using Sketch 52.4

**Comment by dexterbui** [comment]
just manually take the changes from pull request #29. It works :)

**Comment by mcvova** [comment]
Use this fixed version before author merge commit.
https://drive.google.com/open?id=1lvXovbywHYzWjfi08MQUm2hHDkhlR4X6

**Comment by TravisJoe** [comment]
This appears to work just fine for me.
