### ISSUE TITLE
No options after clicking cancel

### ISSUE THREAD

**Issue by username1290** [design4use/gb-sketch-segmentcircle#3]
Updated to latest version and found a bug:
1.- Click "Create segmented circle", 
2.- click Cancel.
3.- Click "Create segmented circle" again
4.- the options window never opens, 

Partially gets solved by clicking "reset values", 
(if you click Cancel, it happens again).

**Comment by design4use** [comment]
Thank you. Will look into this.

**Comment by jameyquinn** [comment]
Confirmed issue here. Clicking Cancel kills the dialog for that tool. Hitting reset makes it available again. So loving this plugin that it made me reconsider sketch as a real tool! Get them to hire you!

**Comment by design4use** [comment]
Thank you, yes the cancel response will be added in the next revision very
shortly!

**Comment by design4use** [comment]
Fixed. Let me know if there are still problems

**Comment by username1290** [comment]
Hi again, 
new version 2.0.1 it seems it's not working.
it creates only the background circle ("base plate"), and skips creating the front ones

**Comment by username1290** [comment]
Re-installed previous version (2.0), previous version works
