### ISSUE TITLE
Not working in Sketch 55

### ISSUE THREAD

**Issue by davemoz** [design4use/gb-sketch-segmentcircle#31]
When I input my options and click "Create circle", an empty folder named "Segmented circle" is created outside of my artboard. No segmented circle shapes inside. I've tried the same process when nothing is selected, when a shape layer is selected, etc, but it simply doesn't work :/ I'm updated to the current latest version of Sketch: v55

**Comment by sebastianknopp** [comment]
Same issue with 51.3

**Comment by design4use** [comment]
Resolved a while ago
