### ISSUE TITLE
Hangs Sketch 3.8.2 / OS X 10.11.5

### ISSUE THREAD

**Issue by adapterdesign** [design4use/gb-sketch-segmentcircle#6]
Hello,
  I've been able to repeatedly hang Sketch when trying to create a Ticks circle with the following values:

![screen shot 2016-05-27 at 10 43 32 am](https://cloud.githubusercontent.com/assets/6933954/15616329/e64dc8e6-23f7-11e6-9d5d-cc9845bc8ad7.png)

I'm assuming that it's due to setting the radii to 0.

**Comment by design4use** [comment]
Correct. Don't set to 0. It won't do any graceful behavior when you set the
radii to 0, maybe one of the next releases.
