### ISSUE TITLE
Empty folders in Sketch 3.8.3 / OSX 10.10.5

### ISSUE THREAD

**Issue by dino-f** [design4use/gb-sketch-segmentcircle#7]
Hi,

I only get empty folders outside my artboards when generating circles. No matter which circle I choose. Any ideas?

Cheers
Dino
[Bildschirmaufnahme.zip](https://github.com/design4use/gb-sketch-segmentcircle/files/315752/Bildschirmaufnahme.zip)

**Comment by Pavithra-olety** [comment]
Hi 

I have the same issue. I get empty folders created outside artboard in the name of the circle type I choose.  Using Sketch Version 40.3 with mac OS sierra version (10.12). Any help?

Thanks 
Pavithra
