### ISSUE TITLE
I broke variable segments circle

### ISSUE THREAD

**Issue by virtualsalvation** [design4use/gb-sketch-segmentcircle#8]
UPDATE: Nevermind. I found the "reset to defaults" fixed it. Thank you!!!

This is an awesome plugin but somehow I broke the only feature I needed which was variable segments circle. When I select that nothing comes up. I can do every other type of circle and the dialog comes up but not "Create variable segments circle". I want to cry.

I should mention I also tried uninstalling and re-installing it several times and even restarting my machine but it did not solve the issue. Any suggestions? It worked the first time I used it but only that first time.

**Comment by design4use** [comment]
Yes that is what I would have suggested. "reset to defaults" resets to a clean slate to start from again.
