### ISSUE TITLE
variable segmented circle stopped working

### ISSUE THREAD

**Issue by vandym** [design4use/gb-sketch-segmentcircle#9]
all the others work ... dialog window for variable segmented circle stopped showing up

**Comment by vandym** [comment]
Any idea why this may be happening, waiting for a solution?

**Comment by CoreyGinnivan** [comment]
Have you tried uninstalling/deleting and reinstalling via Sketch Toolbox? Segmented Circles stopped working for me until I did that. Now everything is good again 👍

**Comment by vandym** [comment]
Thank You @CoreyGinnivan it helped .. I had to "Reset to Defaults" as well!
![screen shot 2016-10-12 at 11 16 06 am](https://cloud.githubusercontent.com/assets/8052783/19322306/54da3f9c-906d-11e6-93de-c33e41f6d859.png)
